import streamlit as st 
import numpy as np 
import requests
from bs4 import BeautifulSoup
import time
from datetime import datetime
import pandas as pd
from bokeh.models.widgets import Div

columns=['Cases','Death','Recovered']

df=pd.DataFrame(columns=columns)
if st.button('Generated by Pratik Ghimire'):
    js = "window.open('https://www.linkedin.com/in/pratik-ghimire/')"  # New tab or window
    js = "window.location.href = 'https://www.linkedin.com/in/pratik-ghimire/'"  # Current tab
    html = '<img src onerror="{}">'.format(js)
    div = Div(text=html)
    st.bokeh_chart(div)


while True:
    nowtime=datetime.now()
    datetimedata=str(nowtime.strftime("%d/%m/%Y %H:%M:%S"))
    date=[]
    date.append(datetimedata)
    URL='https://www.worldometers.info/coronavirus/'
    r=requests.get(URL)
    soup=BeautifulSoup(r.content,'html5lib')

    totalnumbers=soup.findAll('div',attrs={'id':'maincounter-wrap'})

    data=[]

    for result in totalnumbers:
        result=str(result.span.text).replace(",","")
        result=int(result)
        print(result)
        data.append(result)


    entries=len(df)

    df.loc[entries,:]=data
    df.rename(index={entries:date[0]},inplace=True)

    st.title("COVID-19 WORLDWIDE LATEST TREND ((GMT+5.45) NEPAL)")

   

    st.line_chart(data=df,width=0,height=450)

    time.sleep(30)
    